id: I6ED62416
legacy_id: P005499
ocr_import_info:
  bdrc_scan_id: W1KG18169
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T02:29:31'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T09:43:29.600507+00:00'
last_modified: 2022-08-31 17:43:40.018198
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG18169
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG18169
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགའ་ལྷ་རྒྱས་པ་དང་བསྡུས་པའི་བཤད་པ།
  author: ཕ་བོང་ཁ་པ་བདེ་ཆེན་སྙིང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9057006085300175
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG18210:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18210
      total_pages: 262
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG18210.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9057006085300175
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
