id: I6ED62416
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T02:30:06+00:00'
last_modified: '2022-06-08T03:31:16.911930+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18169
  title: དགའ་ལྷ་རྒྱས་པ་དང་བསྡུས་པའི་བཤད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4E20:
      image_group_id: I1KG18210
      title: ''
      total_pages: 262
      order: 1
      base_file: 4E20.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
